before:
  hooks:
    - go mod tidy

builds:
  -
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

archives:
  - 
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
    - '^chore:'
    - '^docs?:'
    - '^test:'
    - '^refactor:'

snapcrafts:
  -
    name: gorched
    publish: true
    summary: Terminal based game inspired by "The Mother of all games" Scorched Earth
    description:  |
      **Gorched** is multiplayer game rendered directly into your terminal.  The goal is to find out correct angle and power to hit the enemy tank.

      The inspiration for this game comes from "The Mother of all games" Scorched Earth.

      **Features**

        * rendered in terminal
        * ASCII graphics (actually few unicode symbols were used in tank sprite)
        * procedurally generated world
        * turn based multiplayer
    license: MIT

brews:
  -
    name: gorched
    github:
      owner: zladovan
      name: homebrew-gorched
    folder: Formula
    homepage: https://github.com/zladovan/gorched
    description: Terminal based game inspired by "The Mother of all games" Scorched Earth
